# Generated by Django 2.2.3 on 2019-11-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20191128_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='element_types', verbose_name='Изображение'),
        ),
    ]
