# Generated by Django 2.2.3 on 2019-11-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemonelementtype_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonelementtype',
            options={'verbose_name': 'Стихия', 'verbose_name_plural': 'Стихии'},
        ),
        migrations.AddField(
            model_name='pokemonelementtype',
            name='weakers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_pokemonelementtype_weakers_+', to='pokemon_entities.PokemonElementType', verbose_name='Силен против'),
        ),
    ]
