# Generated by Django 2.2.3 on 2019-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20191128_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='weakers',
            field=models.ManyToManyField(blank=True, null=True, related_name='strongers', to='pokemon_entities.PokemonElementType', verbose_name='Силен против'),
        ),
    ]
