# Generated by Django 2.2.3 on 2019-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20191128_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='weakers',
            field=models.ManyToManyField(related_name='strongers', to='pokemon_entities.PokemonElementType', verbose_name='Силен против'),
        ),
    ]
