# Generated by Django 2.2.3 on 2019-12-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20191217_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='pokemons', to='pokemon_entities.PokemonElementType', verbose_name='Стихия'),
        ),
    ]
