# Generated by Django 2.2.3 on 2019-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20191217_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='element_type',
            new_name='element_types',
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='weakers',
            field=models.ManyToManyField(blank=True, related_name='strongers', to='pokemon_entities.PokemonElementType', verbose_name='Силен против'),
        ),
    ]
